name: 'Build and test our Eshop'

on:
  workflow_dispach:
  push:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
